const $=s=>document.querySelector(s);let timer;
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(r.status===401){showLogin();throw new Error(d.error||'Nicht angemeldet')}if(!r.ok)throw new Error(d.error||'Fehler');return d}
function showLogin(){$('#login').hidden=false;$('#panel').hidden=true;$('#logout').hidden=true;clearInterval(timer)}function showPanel(){$('#login').hidden=true;$('#panel').hidden=false;$('#logout').hidden=false;load();clearInterval(timer);timer=setInterval(load,2500)}
$('#loginBtn').onclick=async()=>{try{await api('/api/admin/login',{method:'POST',body:JSON.stringify({password:$('#password').value})});$('#loginMsg').textContent='';showPanel()}catch(e){$('#loginMsg').textContent=e.message}};
$('#logout').onclick=async()=>{await fetch('/api/admin/logout',{method:'POST'});showLogin()};$('#refresh').onclick=load;
async function act(body){try{await api('/api/admin/action',{method:'POST',body:JSON.stringify(body)});await load()}catch(e){alert(e.message)}}
window.live=(room,id,action,value)=>act({type:'player',room,id,action,value});window.roomAct=(room,action)=>act({type:'room',room,action});window.stat=(id,field,el)=>act({type:'stat',id,field,value:el.value});window.delStat=id=>confirm('Statistik wirklich löschen?')&&act({type:'deleteStat',id});window.resetRecord=d=>confirm('Record wirklich löschen?')&&act({type:'resetRecord',difficulty:d});
async function load(){try{const d=await api('/api/admin/state');$('#status').textContent=`Freigegeben • ${d.ip}`;$('#roomsN').textContent=d.rooms.length;$('#playersN').textContent=d.rooms.reduce((n,r)=>n+r.players.length,0);$('#uptime').textContent=Math.floor(d.uptime/60)+'m';$('#rooms').innerHTML=d.rooms.length?d.rooms.map(r=>`<div class="room"><div class="title"><div><b>Lobby ${r.id}</b> <span class="pill">${r.mode} • ${r.phase} • ${r.difficulty}</span></div><div class="actions"><button onclick="roomAct('${r.id}','start')">Start</button><button onclick="roomAct('${r.id}','lobby')">Lobby</button><button onclick="roomAct('${r.id}','event')">Event</button><button class="danger" onclick="roomAct('${r.id}','end')">Runde beenden</button></div></div>${r.players.map(p=>`<div class="player"><b>${esc(p.name)} ${p.host?'👑':''}</b><label>Punkte <input value="${p.score}" onchange="live('${r.id}','${p.id}','score',this.value)"></label><label>Coins <input value="${p.coins}" onchange="live('${r.id}','${p.id}','coins',this.value)"></label><label>HP <input value="${p.hp}" onchange="live('${r.id}','${p.id}','hp',this.value)"></label><label>Kills <input value="${p.kills}" onchange="live('${r.id}','${p.id}','kills',this.value)"></label><div class="actions"><button onclick="live('${r.id}','${p.id}','heal',100)">Heilen</button><button class="danger" onclick="live('${r.id}','${p.id}','kill',0)">Kill</button><button class="danger" onclick="live('${r.id}','${p.id}','kick',0)">Kick</button></div></div>`).join('')}</div>`).join(''):'<p class="muted">Keine aktiven Lobbys.</p>';$('#leaderboard').innerHTML=table(d.top);$('#records').innerHTML=d.records.length?d.records.map(x=>`<div class="row"><span><b>${esc(x.difficulty)}</b> — ${esc(x.name)}: ${x.score}</span><button class="danger" onclick="resetRecord('${x.difficulty}')">Record löschen</button></div>`).join(''):'<p class="muted">Keine Records.</p>'}catch(e){if(!String(e.message).includes('angemeldet'))$('#status').textContent=e.message}}
function table(rows){if(!rows.length)return'<p class="muted">Noch keine Daten.</p>';return`<table><tr><th>Name</th><th>Punkte gesamt</th><th>Coins</th><th>Best</th><th>Aktion</th></tr>${rows.map(x=>`<tr><td>${esc(x.name)}</td><td><input value="${x.points}" onchange="stat('${x.id}','points',this)"></td><td><input value="${x.coins}" onchange="stat('${x.id}','coins',this)"></td><td><input value="${x.best}" onchange="stat('${x.id}','best',this)"></td><td><button class="danger" onclick="delStat('${x.id}')">Löschen</button></td></tr>`).join('')}</table>`}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
api('/api/admin/state').then(showPanel).catch(showLogin);
