import { recordGame } from './db.js';

export const W=1600,H=900,MAX=8,ROUND=90000,BATTLE_ROUND=420000;
const rnd=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const CFG={easy:{speed:.78,damage:18,event:[11000,15000],mult:1},normal:{speed:1,damage:28,event:[8000,12000],mult:1},hard:{speed:1.18,damage:38,event:[6200,9200],mult:1.2},chaos:{speed:1.4,damage:48,event:[4300,7000],mult:1.5}};
const EVENTS=['dragon','lantern','baozi','mahjong','panda','golden','chaos','coinStorm','envelope','firecracker'];
const WEAPONS={
 pistol:{name:'Jade Pistol',rarity:'COMMON',damage:18,rate:300,speed:900,mag:12,reload:1250,color:'#d7e8d1'},
 repeater:{name:'Bamboo Repeater',rarity:'RARE',damage:13,rate:125,speed:980,mag:24,reload:1500,color:'#65d887'},
 dragon:{name:'Dragon Blaster',rarity:'EPIC',damage:28,rate:360,speed:760,mag:8,reload:1700,color:'#ff6b45'},
 firecracker:{name:'Firecracker Launcher',rarity:'LEGENDARY',damage:42,rate:720,speed:600,mag:5,reload:2100,color:'#ffd24d'},
 jade:{name:'Jade Beam',rarity:'MYTHIC',damage:22,rate:165,speed:1200,mag:18,reload:1850,color:'#51ffd1'},
 panda:{name:'Panda Cannon',rarity:'LEGENDARY',damage:34,rate:520,speed:690,mag:7,reload:1900,color:'#ffffff'}
};
let uid=0;
const newGun=k=>({key:k,ammo:WEAPONS[k].mag,reloadUntil:0});

export class Game{
 constructor(id,io,onRecord){this.id=id;this.io=io;this.onRecord=onRecord;this.players=new Map();this.host=null;this.phase='lobby';this.difficulty='normal';this.mode='classic';this.battleType='ffa';this.map='temple';this.reset();this.last=Date.now();this.lastEmit=0;this.timer=setInterval(()=>this.tick(),16)}
 destroy(){clearInterval(this.timer)}
 reset(){this.items=[];this.fires=[];this.hazards=[];this.bullets=[];this.weaponDrops=[];this.medkits=[];this.dragon=null;this.banner='';this.bannerUntil=0;this.goldenUntil=0;this.chaosUntil=0;this.nextEvent=0;this.nextBattleSpawn=0;this.ranking=[];this.awards={};this.finishReason=''}
 get online(){return[...this.players.values()].filter(p=>p.sockets.size)}
 fixHost(){if(!this.players.get(this.host)?.sockets.size)this.host=this.online[0]?.id||null}
 join(user,sid){let p=this.players.get(user.id);if(!p){if(this.players.size>=MAX)return null;p={id:user.id,ready:false,spec:this.phase!=='lobby',dead:false,hp:100,maxHp:100,x:W/2,y:H/2,dx:0,dy:0,score:0,coins:0,dragons:0,pandas:0,hits:0,combo:0,bestCombo:0,lastPickup:0,speedUntil:0,magnetUntil:0,shieldUntil:0,ghostUntil:0,doubleUntil:0,hurtUntil:0,kills:0,deaths:0,assists:0,streak:0,bestStreak:0,team:'red',respawnAt:0,lastDamager:null,lastDamageAt:0,lastShot:0,aimX:1,aimY:0,slot:0,guns:[newGun('pistol'),null],special:null,sockets:new Set()};this.players.set(user.id,p)}p.name=user.name;p.avatar=user.avatar;p.skin=user.skin||'letter';p.sockets.add(sid);this.fixHost();this.assignTeams();return p}
 leave(id,sid){const p=this.players.get(id);if(!p)return;p.sockets.delete(sid);p.dx=p.dy=0;if(!p.sockets.size&&this.phase==='lobby')this.players.delete(id);this.fixHost();this.assignTeams()}
 assignTeams(){let i=0;for(const p of this.online)p.team=i++%2?'blue':'red'}
 setReady(id,v){const p=this.players.get(id);if(p&&this.phase==='lobby'&&id!==this.host)p.ready=!!v}
 setDifficulty(id,d){if(id===this.host&&this.phase==='lobby'&&CFG[d])this.difficulty=d}
 setMode(id,m){if(id===this.host&&this.phase==='lobby'&&['classic','battle'].includes(m)){this.mode=m;for(const p of this.players.values())p.ready=false}}
 setBattleType(id,t){if(id===this.host&&this.phase==='lobby'&&['ffa','teams'].includes(t)){this.battleType=t;this.assignTeams();for(const p of this.players.values())p.ready=false}}
 setMap(id,m){if(id===this.host&&this.phase==='lobby'&&['temple','harbor','bamboo'].includes(m))this.map=m}
 setInput(id,dx,dy){const p=this.players.get(id);if(!p||p.spec||p.dead)return;p.dx=clamp(+dx||0,-1,1);p.dy=clamp(+dy||0,-1,1);if(this.mode==='battle'&&Math.hypot(p.dx,p.dy)>.15){const l=Math.hypot(p.dx,p.dy);p.aimX=p.dx/l;p.aimY=p.dy/l}}
 setAim(id,x,y){const p=this.players.get(id);if(!p)return;const l=Math.hypot(x,y)||1;p.aimX=clamp(+x/l||1,-1,1);p.aimY=clamp(+y/l||0,-1,1)}
 switchWeapon(id,slot){const p=this.players.get(id);slot=Number(slot);if(p&&this.mode==='battle'&&(slot===0||slot===1)&&p.guns[slot])p.slot=slot}
 canStart(id){return id===this.host&&(this.phase==='lobby'||this.phase==='over')&&(this.phase==='over'||this.online.every(p=>p.id===this.host||p.ready))}
 prepPlayers(){for(const[k,p]of this.players)if(!p.sockets.size)this.players.delete(k);this.assignTeams();for(const p of this.players.values())Object.assign(p,{spec:false,dead:false,hp:100,maxHp:100,ready:false,score:0,coins:0,dragons:0,pandas:0,hits:0,combo:0,bestCombo:0,lastPickup:0,speedUntil:0,magnetUntil:0,shieldUntil:0,ghostUntil:0,doubleUntil:0,hurtUntil:Date.now()+1500,dx:0,dy:0,x:rnd(180,W-180),y:rnd(180,H-180),kills:0,deaths:0,assists:0,streak:0,bestStreak:0,respawnAt:0,lastDamager:null,lastDamageAt:0,lastShot:0,slot:0,guns:[newGun('pistol'),null]})}
 start(id){if(!this.canStart(id))return;this.reset();this.prepPlayers();this.initialPlayers=this.online.length;this.phase='countdown';this.phaseEnd=Date.now()+3000}
 backToLobby(id){if(id!==this.host||this.phase!=='over')return;this.reset();for(const p of this.players.values())Object.assign(p,{ready:false,spec:false,dead:false,hp:100,score:0,combo:0,dx:0,dy:0,kills:0,deaths:0,streak:0});this.phase='lobby';this.emit(Date.now())}
 addItem(type,v,life=20000,x=rnd(80,W-80),y=rnd(100,H-80)){this.items.push({id:++uid,type,v,x,y,until:Date.now()+life})}
 event(now){const k=EVENTS[Math.floor(Math.random()*EVENTS.length)],names={dragon:'🐉 DRAGON ATTACK!',lantern:'🏮 LANTERN RUSH!',baozi:'🥟 BAOZI RAIN!',mahjong:'🀄 MAHJONG BONUS!',panda:'🐼 PANDA MODE!',golden:'💰 GOLDEN LUCK!',chaos:'🌪️ CHAOS MODE!',coinStorm:'🪙 COIN STORM!',envelope:'🧧 RED ENVELOPE RUSH!',firecracker:'💥 FIRECRACKER CHAOS!'};this.banner=names[k];this.bannerUntil=now+2500;this.bannerKind=k;if(k==='dragon'&&!this.dragon)this.dragon={x:-120,y:rnd(160,H-160),vx:520*CFG[this.difficulty].speed,t:0};if(k==='lantern')for(let i=0;i<14;i++)this.addItem('lantern',25);if(k==='baozi')for(let i=0;i<18;i++)this.addItem('baozi',15,12000);if(k==='mahjong')this.addItem('mahjong',150,15000);if(k==='panda')this.addItem('panda',50,15000);if(k==='golden')this.goldenUntil=now+10000;if(k==='chaos')this.chaosUntil=now+5000;if(k==='coinStorm')for(let i=0;i<35;i++)this.addItem('coin',10,12000);if(k==='envelope')for(let i=0;i<16;i++)this.addItem('envelope',Math.random()<.15?100:30,13000);if(k==='firecracker')for(let i=0;i<8;i++)this.hazards.push({id:++uid,x:rnd(100,W-100),y:rnd(120,H-100),boomAt:now+2500+rnd(0,1500),until:now+5000})}
 tick(){const now=Date.now(),dt=Math.min((now-this.last)/1000,.1);this.last=now;if(this.phase==='countdown'&&now>=this.phaseEnd){this.phase='playing';this.endAt=now+(this.mode==='battle'?BATTLE_ROUND:ROUND);this.nextEvent=now+3500;this.nextBattleSpawn=now+1200}if(this.phase==='playing'){this.mode==='battle'?this.playBattle(now,dt):this.playClassic(now,dt)}if(now-this.lastEmit>=33){this.lastEmit=now;this.emit(now)}}
 hit(p,damage,now,kx=0,ky=0){if(p.dead||now<p.hurtUntil||now<p.ghostUntil)return false;if(now<p.shieldUntil){p.shieldUntil=0;p.hurtUntil=now+650;return false}p.hurtUntil=now+700;p.hits++;p.hp=Math.max(0,p.hp-damage);p.x=clamp(p.x+kx+rnd(-10,10),30,W-30);p.y=clamp(p.y+ky+rnd(-10,10),60,H-30);if(p.hp<=0){p.dead=true;p.spec=true;p.dx=p.dy=0;p.combo=0}return true}
 pickup(p,it,now){it.taken=true;p.combo=now-p.lastPickup<3000?p.combo+1:1;p.lastPickup=now;p.bestCombo=Math.max(p.bestCombo,p.combo);const mult=(now<this.goldenUntil?2:1)*(now<p.doubleUntil?2:1)*CFG[this.difficulty].mult*(1+Math.min(p.combo-1,9)*.05);if(it.type==='coin'){p.coins++;p.score+=Math.round(it.v*mult)}else if(it.type==='panda'){p.pandas++;p.speedUntil=now+6000;p.score+=Math.round(it.v*mult)}else if(it.type==='magnet')p.magnetUntil=now+7000;else if(it.type==='shield')p.shieldUntil=now+10000;else if(it.type==='double')p.doubleUntil=now+8000;else if(it.type==='ghost')p.ghostUntil=now+6000;else p.score+=Math.round(it.v*mult)}
 tryPickup(id,itemId,cx,cy){const p=this.players.get(id);if(!p||this.mode!=='classic'||this.phase!=='playing'||p.dead||p.spec)return;const it=this.items.find(i=>i.id===Number(itemId)&&!i.taken);if(!it)return;cx=Number(cx);cy=Number(cy);if(!Number.isFinite(cx)||!Number.isFinite(cy))return;const visualRadius=it.type==='coin'?36:50;/* Lag compensation: client may be ahead of authoritative position, but never trust a teleport. */if(Math.hypot(cx-p.x,cy-p.y)>145)return;if(Math.hypot(cx-it.x,cy-it.y)>visualRadius)return;this.pickup(p,it,Date.now());this.items=this.items.filter(i=>!i.taken)}
 movePlayers(now,dt,classic=false){for(const p of this.players.values()){if(p.spec||p.dead)continue;if(classic&&now-p.lastPickup>3000)p.combo=0;let dx=classic&&now<this.chaosUntil?-p.dx:p.dx,dy=classic&&now<this.chaosUntil?-p.dy:p.dy,mag=Math.min(1,Math.hypot(dx,dy)),len=Math.hypot(dx,dy)||1,sp=(now<p.speedUntil?440:285)*mag;p.x=clamp(p.x+dx/len*sp*dt,30,W-30);p.y=clamp(p.y+dy/len*sp*dt,60,H-30)}}
 playClassic(now,dt){const cfg=CFG[this.difficulty];this.movePlayers(now,dt,true);for(const p of this.players.values())if(!p.dead&&!p.spec&&now<p.magnetUntil)for(const it of this.items){if(it.taken||it.type!=='coin')continue;const dd=Math.hypot(p.x-it.x,p.y-it.y);if(dd<220){it.x+=(p.x-it.x)*dt*4;it.y+=(p.y-it.y)*dt*4}}if(now>=this.nextEvent){this.event(now);this.nextEvent=now+rnd(...cfg.event)}if(this.items.filter(i=>i.type==='coin').length<26)for(let i=0;i<3;i++)this.addItem('coin',10,1e9);if(Math.random()<.002)this.addItem(['magnet','shield','double','ghost'][Math.floor(Math.random()*4)],0,15000);this.items=this.items.filter(i=>i.until>now);if(this.dragon){const d=this.dragon;d.x+=d.vx*dt;d.t+=dt;if(d.t>.18/CFG[this.difficulty].speed){d.t=0;this.fires.push({x:d.x+60,y:d.y+rnd(-45,45),vx:190*cfg.speed,until:now+4800})}if(d.x>W+150){for(const p of this.players.values())if(!p.spec&&!p.dead&&p.sockets.size)p.dragons++;this.dragon=null}}for(const f of this.fires)f.x+=f.vx*dt;this.fires=this.fires.filter(f=>f.until>now&&f.x<W+100);for(const h of this.hazards)if(now>=h.boomAt&&!h.done)h.done=true;this.hazards=this.hazards.filter(h=>h.until>now);for(const p of this.players.values()){if(p.spec||p.dead)continue;if(this.dragon&&dist(this.dragon,p)<82)this.hit(p,cfg.damage,now,55,0);for(const f of this.fires)if(dist(f,p)<48)this.hit(p,cfg.damage,now,35,0);for(const h of this.hazards)if(h.done&&now-h.boomAt<400&&dist(h,p)<92)this.hit(p,cfg.damage,now,(p.x-h.x)*.35,(p.y-h.y)*.35);for(const it of this.items){if(it.taken)continue;const radius=it.type==='coin'?29:43;if(dist(it,p)<radius)this.pickup(p,it,now)}}this.items=this.items.filter(i=>!i.taken);const active=[...this.players.values()].filter(p=>!p.dead&&!p.spec&&p.sockets.size);if(this.initialPlayers<=1&&active.length===0)return this.finish('dead');if(this.initialPlayers>1&&active.length<=1)return this.finish(active.length===1?'last-alive':'all-dead');if(now>=this.endAt)this.finish('time')}
 spawnBattleLoot(now){const keys=['repeater','dragon','firecracker','jade','panda'];if(this.weaponDrops.length<7)this.weaponDrops.push({id:++uid,key:keys[Math.floor(Math.random()*keys.length)],x:rnd(100,W-100),y:rnd(100,H-100),until:now+30000});if(this.medkits.length<5)this.medkits.push({id:++uid,x:rnd(100,W-100),y:rnd(100,H-100),until:now+25000});this.nextBattleSpawn=now+5000}
 shoot(id){if(this.mode!=='battle'||this.phase!=='playing')return;const now=Date.now(),p=this.players.get(id);if(!p||p.dead||p.spec||now<p.respawnAt)return;const gun=p.guns[p.slot];if(!gun)return;const w=WEAPONS[gun.key];if(now<gun.reloadUntil||now-p.lastShot<w.rate)return;if(gun.ammo<=0){gun.reloadUntil=now+w.reload;p.lastShot=now;return}gun.ammo--;p.lastShot=now;const spread=(Math.random()-.5)*(gun.key==='repeater'?.07:.035),c=Math.cos(spread),s=Math.sin(spread),ax=p.aimX*c-p.aimY*s,ay=p.aimX*s+p.aimY*c;this.bullets.push({id:++uid,owner:p.id,team:p.team,x:p.x+ax*36,y:p.y+ay*36,vx:ax*w.speed,vy:ay*w.speed,damage:w.damage,key:gun.key,until:now+1800});if(gun.ammo===0)gun.reloadUntil=now+w.reload}
 reload(id){const p=this.players.get(id);if(!p||this.mode!=='battle')return;const g=p.guns[p.slot];if(g&&g.ammo<WEAPONS[g.key].mag)g.reloadUntil=Date.now()+WEAPONS[g.key].reload}
 battleDamage(target,bullet,now){const shooter=this.players.get(bullet.owner);if(!shooter||target.id===shooter.id)return false;if(this.battleType==='teams'&&target.team===shooter.team)return false;if(target.dead||now<target.hurtUntil)return false;target.hurtUntil=now+180;target.hp=Math.max(0,target.hp-bullet.damage);target.lastDamager=shooter.id;target.lastDamageAt=now;if(target.hp<=0){target.dead=true;target.spec=true;target.deaths++;target.respawnAt=now+5000;target.dx=target.dy=0;shooter.kills++;shooter.score=shooter.kills;shooter.streak++;shooter.bestStreak=Math.max(shooter.bestStreak,shooter.streak);target.streak=0;for(const g of target.guns.slice(1))if(g)this.weaponDrops.push({id:++uid,key:g.key,x:target.x+rnd(-25,25),y:target.y+rnd(-25,25),until:now+18000});target.guns=[newGun('pistol'),null];target.slot=0;this.banner=`💥 ${shooter.name} eliminierte ${target.name}`;this.bannerKind='kill';this.bannerUntil=now+1400}return true}
 respawn(p,now){p.dead=false;p.spec=false;p.hp=100;p.x=rnd(120,W-120);p.y=rnd(120,H-120);p.hurtUntil=now+1800;p.respawnAt=0;p.lastDamager=null}
 playBattle(now,dt){this.movePlayers(now,dt,false);if(now>=this.nextBattleSpawn)this.spawnBattleLoot(now);for(const p of this.players.values()){if(p.dead&&p.sockets.size&&now>=p.respawnAt)this.respawn(p,now);if(!p.dead&&now-p.lastDamageAt>8000&&p.hp<100)p.hp=Math.min(100,p.hp+8*dt);for(const g of p.guns)if(g?.reloadUntil&&now>=g.reloadUntil){g.ammo=WEAPONS[g.key].mag;g.reloadUntil=0}}
 for(const b of this.bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.x<0||b.x>W||b.y<0||b.y>H)b.until=0;for(const p of this.players.values()){if(b.until<=0||p.dead||p.spec||p.id===b.owner)continue;if(Math.hypot(b.x-p.x,b.y-p.y)<31&&this.battleDamage(p,b,now))b.until=0}}this.bullets=this.bullets.filter(b=>b.until>now);
 this.weaponDrops=this.weaponDrops.filter(g=>g.until>now&&!g.taken);this.medkits=this.medkits.filter(m=>m.until>now&&!m.taken);for(const p of this.players.values()){if(p.dead||p.spec)continue;for(const g of this.weaponDrops)if(!g.taken&&dist(g,p)<35){g.taken=true;const ng=newGun(g.key);if(!p.guns[1]){p.guns[1]=ng;p.slot=1}else p.guns[p.slot]=ng}for(const m of this.medkits)if(!m.taken&&p.hp<100&&dist(m,p)<30){m.taken=true;p.hp=Math.min(100,p.hp+35)}}
 this.weaponDrops=this.weaponDrops.filter(g=>!g.taken);this.medkits=this.medkits.filter(m=>!m.taken);if(now>=this.endAt)this.finishBattle('time')}
 finishBattle(reason){if(this.phase==='over')return;this.phase='over';this.finishReason=reason;const list=[...this.players.values()].filter(p=>p.sockets.size);list.sort((a,b)=>b.kills-a.kills||a.deaths-b.deaths);this.ranking=list.map(p=>({id:p.id,name:p.name,avatar:p.avatar,score:p.kills,kills:p.kills,deaths:p.deaths,bestStreak:p.bestStreak,team:p.team,hp:p.hp,dead:false}));const top=list[0];this.awards={killer:top?.name,streak:[...list].sort((a,b)=>b.bestStreak-a.bestStreak)[0]?.name,survivor:[...list].sort((a,b)=>a.deaths-b.deaths)[0]?.name};for(const p of this.players.values()){p.ready=false;p.dx=p.dy=0}}
 finish(reason='time'){if(this.phase==='over')return;this.phase='over';this.finishReason=reason;const list=[...this.players.values()].filter(p=>p.sockets.size).sort((a,b)=>(Number(a.dead)-Number(b.dead))||(b.score-a.score));this.ranking=list.map(p=>({id:p.id,name:p.name,avatar:p.avatar,score:p.score,coins:p.coins,hits:p.hits,bestCombo:p.bestCombo,dead:p.dead,hp:p.hp}));const survivors=list.filter(p=>!p.dead),winner=survivors.sort((a,b)=>b.score-a.score)[0]||null,coin=[...list].sort((a,b)=>b.coins-a.coins)[0],combo=[...list].sort((a,b)=>b.bestCombo-a.bestCombo)[0],dodger=[...list].sort((a,b)=>a.hits-b.hits)[0];this.awards={coin:coin?.name,combo:combo?.name,dodger:dodger?.name};for(const p of list){const r=recordGame(p,winner?.id===p.id,this.difficulty);if(r.broken)this.onRecord?.(r)}for(const p of this.players.values()){p.ready=false;p.dx=p.dy=0}}
 emit(now){this.io.to(this.id).emit('state',{phase:this.phase,host:this.host,mode:this.mode,battleType:this.battleType,map:this.map,difficulty:this.difficulty,finishReason:this.finishReason,left:this.phase==='playing'?Math.max(0,this.endAt-now):(this.mode==='battle'?BATTLE_ROUND:ROUND),cd:this.phase==='countdown'?Math.max(0,Math.ceil((this.phaseEnd-now)/1000)):0,banner:now<this.bannerUntil?this.banner:'',kind:this.bannerKind,golden:now<this.goldenUntil,chaos:now<this.chaosUntil,players:[...this.players.values()].map(p=>({id:p.id,name:p.name,avatar:p.avatar,skin:p.skin,x:p.x,y:p.y,score:p.score,ready:p.ready,spec:p.spec,dead:p.dead,hp:Math.round(p.hp),maxHp:p.maxHp,on:p.sockets.size>0,fast:now<p.speedUntil,hurt:now<p.hurtUntil,combo:p.combo,kills:p.kills,deaths:p.deaths,streak:p.streak,team:p.team,respawn:Math.max(0,p.respawnAt-now),slot:p.slot,guns:p.guns.map(g=>g?{key:g.key,name:WEAPONS[g.key].name,rarity:WEAPONS[g.key].rarity,ammo:g.ammo,mag:WEAPONS[g.key].mag,reload:Math.max(0,g.reloadUntil-now)}:null),powers:{magnet:Math.max(0,p.magnetUntil-now),shield:Math.max(0,p.shieldUntil-now),double:Math.max(0,p.doubleUntil-now),ghost:Math.max(0,p.ghostUntil-now)}})),items:this.items.map(i=>({id:i.id,t:i.type,x:i.x,y:i.y})),fires:this.fires.map(f=>({x:f.x,y:f.y})),hazards:this.hazards.map(h=>({x:h.x,y:h.y,boom:h.done})),dragon:this.dragon?{x:this.dragon.x,y:this.dragon.y}:null,bullets:this.bullets.map(b=>({x:b.x,y:b.y,key:b.key})),weaponDrops:this.weaponDrops.map(g=>({x:g.x,y:g.y,key:g.key,name:WEAPONS[g.key].name,rarity:WEAPONS[g.key].rarity})),medkits:this.medkits.map(m=>({x:m.x,y:m.y})),ranking:this.ranking,awards:this.awards})}
}
