import 'dotenv/config'; import crypto from 'crypto'; import express from 'express'; import http from 'http'; import path from 'path'; import fs from 'fs'; import {fileURLToPath} from 'url'; import {Server} from 'socket.io'; import rateLimit from 'express-rate-limit'; import {startBot,announceRecord} from './bot.js'; import {Game} from './game.js'; import {top,records,adminSetStat,adminDeleteStats,adminResetRecord,closeDb} from './db.js';
const dist=path.join(path.dirname(fileURLToPath(import.meta.url)),'../client/dist');const app=express();app.set('trust proxy',1);app.disable('x-powered-by');app.use(express.json({limit:'10kb'}));app.use('/api',rateLimit({windowMs:60000,limit:180}));
app.get('/api/config',(_,res)=>res.json({clientId:process.env.DISCORD_CLIENT_ID||'',guest:process.env.ALLOW_GUEST==='true'}));app.get('/api/leaderboard',(_,res)=>res.json({top:top(10),records:records()}));
app.post('/api/token',async(req,res)=>{const code=req.body?.code;if(typeof code!=='string'||code.length>200)return res.status(400).json({error:'bad code'});try{const r=await fetch('https://discord.com/api/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:process.env.DISCORD_CLIENT_ID||'',client_secret:process.env.DISCORD_CLIENT_SECRET||'',grant_type:'authorization_code',code})});const d=await r.json();if(!r.ok)return res.status(400).json({error:'discord rejected'});res.json({access_token:d.access_token})}catch{res.status(500).json({error:'token error'})}});
app.use(express.static(dist));const server=http.createServer(app),io=new Server(server,{maxHttpBufferSize:4096,cors:{origin:false}}),rooms=new Map();

// ---- Admin panel: server-side IP allowlist + optional password ----
const ADMIN_IP=process.env.ADMIN_ALLOWED_IP||'178.39.54.112';
const ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'';
const adminSessions=new Map();
function requestIp(req){const f=String(req.headers['x-forwarded-for']||'').split(',')[0].trim();return (f||req.ip||req.socket.remoteAddress||'').replace(/^::ffff:/,'')}
function ipAllowed(req){return requestIp(req)===ADMIN_IP}
function cookies(req){return Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim().split('=').map(decodeURIComponent)).filter(x=>x.length===2))}
function adminAuthed(req){if(!ipAllowed(req))return false;if(!ADMIN_PASSWORD)return true;const token=cookies(req).cc_admin;const exp=adminSessions.get(token);if(!token||!exp||exp<Date.now()){if(token)adminSessions.delete(token);return false}return true}
function adminOnly(req,res,next){if(!ipAllowed(req))return res.status(404).send('Not found');if(!adminAuthed(req))return res.status(401).json({error:'Admin-Anmeldung erforderlich'});next()}
app.get('/admin',(req,res)=>{if(!ipAllowed(req))return res.status(404).send('Not found');res.sendFile(path.join(path.dirname(fileURLToPath(import.meta.url)),'../client/admin.html'))});
app.get('/admin.css',(req,res)=>{if(!ipAllowed(req))return res.status(404).end();res.sendFile(path.join(path.dirname(fileURLToPath(import.meta.url)),'../client/admin.css'))});
app.get('/admin.js',(req,res)=>{if(!ipAllowed(req))return res.status(404).end();res.sendFile(path.join(path.dirname(fileURLToPath(import.meta.url)),'../client/admin.js'))});
app.post('/api/admin/login',(req,res)=>{if(!ipAllowed(req))return res.status(404).json({error:'Not found'});if(ADMIN_PASSWORD&&String(req.body?.password||'')!==ADMIN_PASSWORD)return res.status(401).json({error:'Falsches Passwort'});const token=crypto.randomBytes(32).toString('hex');adminSessions.set(token,Date.now()+12*60*60*1000);res.setHeader('Set-Cookie',`cc_admin=${token}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=43200`);res.json({ok:true})});
app.post('/api/admin/logout',(req,res)=>{const t=cookies(req).cc_admin;if(t)adminSessions.delete(t);res.setHeader('Set-Cookie','cc_admin=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0');res.json({ok:true})});
app.get('/api/admin/state',adminOnly,(req,res)=>res.json({ip:requestIp(req),uptime:process.uptime(),rooms:[...rooms.entries()].map(([id,g])=>({id,phase:g.phase,mode:g.mode,difficulty:g.difficulty,battleType:g.battleType,map:g.map,players:[...g.players.values()].filter(p=>p.sockets.size).map(p=>({id:p.id,name:p.name,score:p.score,coins:p.coins,hp:Math.round(p.hp),kills:p.kills,deaths:p.deaths,host:p.id===g.host}))})),top:top(50),records:records()}));
app.post('/api/admin/action',adminOnly,(req,res)=>{try{const b=req.body||{};if(b.type==='stat'){adminSetStat(b.id,b.field,b.value);return res.json({ok:true})}if(b.type==='deleteStat'){adminDeleteStats(b.id);return res.json({ok:true})}if(b.type==='resetRecord'){adminResetRecord(b.difficulty);return res.json({ok:true})}const g=rooms.get(cleanCode(b.room));if(!g)return res.status(404).json({error:'Lobby nicht gefunden'});if(b.type==='room'){if(b.action==='start')g.start(g.host);else if(b.action==='lobby'){if(g.phase==='over')g.backToLobby(g.host);else{g.reset();g.phase='lobby';for(const p of g.players.values()){p.ready=false;p.spec=false;p.dead=false;p.hp=100;p.dx=p.dy=0}g.emit(Date.now())}}else if(b.action==='end'){g.mode==='battle'?g.finishBattle('admin'):g.finish('admin')}else if(b.action==='event'&&g.mode==='classic'&&g.phase==='playing')g.event(Date.now());else return res.status(400).json({error:'Ungültige Raum-Aktion'});return res.json({ok:true})}if(b.type==='player'){const p=g.players.get(String(b.id));if(!p)return res.status(404).json({error:'Spieler nicht gefunden'});const v=Math.trunc(Number(b.value)||0);if(b.action==='score')p.score=Math.max(0,v);else if(b.action==='coins')p.coins=Math.max(0,v);else if(b.action==='kills'){p.kills=Math.max(0,v);p.score=g.mode==='battle'?p.kills:p.score}else if(b.action==='hp'){p.hp=Math.max(0,Math.min(p.maxHp||100,v));if(p.hp>0){p.dead=false;p.spec=false}}else if(b.action==='heal'){p.hp=p.maxHp||100;p.dead=false;p.spec=false}else if(b.action==='kill'){p.hp=0;p.dead=true;p.spec=true;p.dx=p.dy=0}else if(b.action==='kick'){for(const sid of [...p.sockets])io.sockets.sockets.get(sid)?.disconnect(true);g.players.delete(p.id);g.fixHost();g.assignTeams()}else return res.status(400).json({error:'Ungültige Spieler-Aktion'});g.emit(Date.now());return res.json({ok:true})}res.status(400).json({error:'Ungültige Aktion'})}catch(e){console.error('Admin action:',e);res.status(500).json({error:'Admin-Aktion fehlgeschlagen'})}});

const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';function code(){let c='';do{c='';for(let i=0;i<6;i++)c+=alphabet[Math.floor(Math.random()*alphabet.length)]}while(rooms.has(c));return c}function cleanCode(c){return String(c||'').toUpperCase().replace(/[^A-Z2-9]/g,'').slice(0,6)}function cleanName(n){return String(n||'').replace(/[^\p{L}\p{N} _-]/gu,'').trim().slice(0,16)}function guestId(socket,device){const raw=socket.handshake.address||'unknown';const safeDevice=String(device||'device').replace(/[^a-zA-Z0-9_-]/g,'').slice(0,64);const secret=process.env.IP_HASH_SECRET||process.env.DISCORD_CLIENT_SECRET||'china-chaos-local-dev';return 'ip-'+crypto.createHmac('sha256',secret).update(raw+'|'+safeDevice).digest('hex').slice(0,24)}
async function verify(token,name){const r=await fetch('https://discord.com/api/users/@me',{headers:{Authorization:'Bearer '+token}});if(!r.ok)return null;const u=await r.json();return{id:u.id,name:cleanName(name)||cleanName(u.global_name||u.username)||'Spieler',avatar:u.avatar?`https://cdn.discordapp.com/avatars/${u.id}/${u.avatar}.png?size=64`:''}}
function verifyLinkAuth(ticket,name){try{const [payload,sig]=String(ticket||'').split('.');if(!payload||!sig)return null;const secret=process.env.IP_HASH_SECRET||process.env.DISCORD_CLIENT_SECRET;if(!secret)return null;const expected=crypto.createHmac('sha256',secret).update(payload).digest();const got=Buffer.from(sig,'base64url');if(got.length!==expected.length||!crypto.timingSafeEqual(got,expected))return null;const d=JSON.parse(Buffer.from(payload,'base64url').toString('utf8'));if(!d.id||!d.exp||Date.now()>d.exp)return null;return{id:String(d.id),name:cleanName(name)||cleanName(d.name)||'Spieler',avatar:String(d.avatar||'').slice(0,500)}}catch{return null}}
io.on('connection',socket=>{let game=null,uid=null,msgs=0;const bucket=setInterval(()=>msgs=0,1000),ok=()=>++msgs<=120;socket.on('create',async d=>{if(game)return;let user=null;try{if(d?.auth)user=verifyLinkAuth(d.auth,d.name);else if(d?.token)user=await verify(d.token,d.name);else if(process.env.ALLOW_GUEST==='true'){const name=cleanName(d?.name);if(name.length<2)return socket.emit('err','Name muss 2–16 Zeichen haben.');user={id:guestId(socket,d?.device),name,avatar:''}}}catch{}if(!user)return socket.emit('err','Login fehlgeschlagen');user.skin=['discord','flag','letter'].includes(d?.skin)?d.skin:'letter';if(user.skin==='discord'&&!user.avatar)user.skin='letter';const room=code();game=new Game(room,io,announceRecord);rooms.set(room,game);game.join(user,socket.id);uid=user.id;socket.join(room);socket.emit('joined',{id:uid,room})});socket.on('join',async d=>{if(game)return;const room=cleanCode(d?.room);const g=rooms.get(room);if(!g)return socket.emit('err','Gruppe nicht gefunden.');let user=null;try{if(d?.auth)user=verifyLinkAuth(d.auth,d.name);else if(d?.token)user=await verify(d.token,d.name);else if(process.env.ALLOW_GUEST==='true'){const name=cleanName(d?.name);if(name.length<2)return socket.emit('err','Name muss 2–16 Zeichen haben.');user={id:guestId(socket,d?.device),name,avatar:''}}}catch{}if(!user)return socket.emit('err','Login fehlgeschlagen');user.skin=['discord','flag','letter'].includes(d?.skin)?d.skin:'letter';if(user.skin==='discord'&&!user.avatar)user.skin='letter';if(!g.join(user,socket.id))return socket.emit('err','Gruppe ist voll.');game=g;uid=user.id;socket.join(room);socket.emit('joined',{id:uid,room})});socket.on('input',d=>{if(game&&ok()&&d)game.setInput(uid,d.dx,d.dy)});socket.on('pickup',d=>{if(game&&ok()&&d)game.tryPickup(uid,d.id,d.x,d.y)});socket.on('ready',v=>{if(game&&ok())game.setReady(uid,v)});socket.on('difficulty',v=>{if(game&&ok())game.setDifficulty(uid,v)});socket.on('mode',v=>{if(game&&ok())game.setMode(uid,v)});socket.on('battleType',v=>{if(game&&ok())game.setBattleType(uid,v)});socket.on('map',v=>{if(game&&ok())game.setMap(uid,v)});socket.on('aim',d=>{if(game&&ok()&&d)game.setAim(uid,d.x,d.y)});socket.on('shoot',()=>{if(game&&ok())game.shoot(uid)});socket.on('reload',()=>{if(game&&ok())game.reload(uid)});socket.on('switch',v=>{if(game&&ok())game.switchWeapon(uid,v)});socket.on('start',()=>{if(game&&ok())game.start(uid)});socket.on('lobby',()=>{if(game&&ok())game.backToLobby(uid)});socket.on('disconnect',()=>{clearInterval(bucket);game?.leave(uid,socket.id)})});
setInterval(()=>{for(const[k,g]of rooms)if(!g.online.length){g.destroy();rooms.delete(k)}},30000);const port=process.env.PORT||3000;server.listen(port,()=>console.log(`🐉 China Chaos läuft auf http://localhost:${port}`));if(process.env.RUN_DISCORD_BOT!=='false')startBot().catch(e=>console.error('Bot:',e.message));else console.log('🌐 Render-Modus: Discord Bot deaktiviert');const bye=()=>{io.close();closeDb();process.exit(0)};process.on('SIGINT',bye);process.on('SIGTERM',bye);
